# Made by Agazed
# Visit me @ agazed.net!

# Vars: %PLACED_PLAYER%, %PLACER_PLAYER%, %KILLER%, %AMOUNT%
bounty-placed:
- broadcast Bounty was placed on %PLACED_PLAYER% for $%AMOUNT%!
bounty-removed:
- broadcast Bounty was removed on %PLACED_PLAYER%!
bounty-player-killed:
- broadcast Bountied player %PLACED_PLAYER% was slain by %KILLER%!

# Don't touch this
bounties: {}
